services:
  mannequin-segmenter:
    build: ./mannequin-segmenter
    container_name: mannequin-segmenter
    ports:
      - "5001:5000"
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped

  category-predictor:
    build: ./garment-category-predictor
    container_name: category-predictor
    ports:
      - "5002:5000"
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped

  measuring-hpe:
    build: ./garment-measuring-hpe
    container_name: measuring-hpe
    ports:
      - "5003:5000"
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped

  attribute-predictor:
    build: ./openai-api-garment-attribute-predictor
    container_name: attribute-predictor
    ports:
      - "5004:5000"
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped

  main-orchestrator:
    build: .
    container_name: main-orchestrator
    ports:
      - "5000:5000"
    volumes:
      - ./reports:/app/reports
      - ./CWS_Test:/app/CWS_Test
    environment:
      - PYTHONUNBUFFERED=1
      # Use the service names (not container names) for internal communication
      - MANNEQUIN_SEGMENTER_HOST=mannequin-segmenter
      - MANNEQUIN_SEGMENTER_PORT=5001
      - CATEGORY_PREDICTOR_HOST=category-predictor
      - CATEGORY_PREDICTOR_PORT=5002
      - MEASURING_HPE_HOST=measuring-hpe
      - MEASURING_HPE_PORT=5003
      - ATTRIBUTE_PREDICTOR_HOST=attribute-predictor
      - ATTRIBUTE_PREDICTOR_PORT=5004
    depends_on:
      - mannequin-segmenter
      - category-predictor
      - measuring-hpe
      - attribute-predictor
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped