FROM python:3.9-slim

WORKDIR /app

# Copy requirements and install dependencies first (for better caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY main.py .
COPY category_mapper.py .  
COPY pdf_generator.py .
COPY .env* ./
COPY background.pdf .
COPY fonts/Libre_Baskerville /app/fonts/Libre_Baskerville
# COPY CWS_Test /app/CWS_Test
# COPY peteava /app/peteava
EXPOSE 5000

CMD ["python", "main.py"]