version: '3.8'

services:
  garment-measuring-hpe:
    build: .
    ports:
      - "5003:5003"
    environment:
      # Application settings
      - FLASK_APP=api_app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5003
      - PYTHONPATH=/app
      
      # GCP credentials for model download (optional for local dev)
      # Uncomment and set these if you want to test GCP download locally
      # - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      # - GCP_SA_KEY=${GCP_SA_KEY}
      # - BUCKET_NAME_ARTIFACTS=${BUCKET_NAME_ARTIFACTS:-artifactsredi}
      
      # Force GCP behavior for testing (uncomment to test GCP mode locally)
      # - GOOGLE_CLOUD_PROJECT=test-project
      
    volumes:
      # Mount local artifacts directory to use existing models
      - ./artifacts:/app/artifacts:ro  # Read-only mount for security
      
      # Mount logs directory for debugging
      - ./logs:/app/logs
      
      # Optional: Mount source code for development (live reload)
      # - ./api_app.py:/app/api_app.py
      # - ./tools:/app/tools
      
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s