name: Download Garment Measuring HPE Models

on:
  workflow_dispatch:
    inputs:
      force_download:
        description: 'Force re-download even if files exist'
        required: false
        default: false
        type: boolean

jobs:
  download-hpe-models:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage google-auth
        
    - name: Download HPE models from GCP
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        BUCKET_NAME_ARTIFACTS: ${{ secrets.BUCKET_NAME_ARTIFACTS }}
        FORCE_DOWNLOAD: ${{ github.event.inputs.force_download }}
      working-directory: garment-measuring-hpe
      run: |
        if [ "$FORCE_DOWNLOAD" = "true" ]; then
          # If force download, remove existing files first
          rm -f artifacts/pose_hrnet-w48_384x288-deepfashion2_mAP_0.7017.pth
          rm -f artifacts/bbox_result_val.pkl
        fi
        python download_models.py
        
    - name: Verify downloads
      working-directory: garment-measuring-hpe
      run: |
        echo "=== Verifying downloaded files ==="
        
        if [ -f "artifacts/pose_hrnet-w48_384x288-deepfashion2_mAP_0.7017.pth" ]; then
          echo "✅ HRNet pose model downloaded successfully"
          ls -lh artifacts/pose_hrnet-w48_384x288-deepfashion2_mAP_0.7017.pth
        else
          echo "❌ HRNet pose model not found after download"
          exit 1
        fi
        
        if [ -f "artifacts/bbox_result_val.pkl" ]; then
          echo "✅ Bbox result file downloaded successfully"
          ls -lh artifacts/bbox_result_val.pkl
        else
          echo "❌ Bbox result file not found after download"
          exit 1
        fi
        
        echo "✅ All HPE model files verified successfully!"
        
    - name: Upload models as artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: garment-measuring-hpe-models
        path: |
          garment-measuring-hpe/artifacts/pose_hrnet-w48_384x288-deepfashion2_mAP_0.7017.pth
          garment-measuring-hpe/artifacts/bbox_result_val.pkl
        retention-days: 7 