name: Download Mannequin Segmenter Model

on:
  workflow_dispatch:
    inputs:
      force_download:
        description: 'Force re-download even if file exists'
        required: false
        default: false
        type: boolean

jobs:
  download-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage google-auth
        
    - name: Download model from GCP
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        BUCKET_NAME_ARTIFACTS: ${{ secrets.BUCKET_NAME_ARTIFACTS }}
        FORCE_DOWNLOAD: ${{ github.event.inputs.force_download }}
      working-directory: mannequin-segmenter
      run: |
        if [ "$FORCE_DOWNLOAD" = "true" ]; then
          # If force download, remove existing file first
          rm -f artifacts/20250703_190222/checkpoint.pt
        fi
        python download_model.py
        
    - name: Verify download
      working-directory: mannequin-segmenter
      run: |
        if [ -f "artifacts/20250703_190222/checkpoint.pt" ]; then
          echo "✅ Model file downloaded successfully"
          ls -lh artifacts/20250703_190222/checkpoint.pt
        else
          echo "❌ Model file not found after download"
          exit 1
        fi
        
    - name: Upload model as artifact (optional)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: mannequin-segmenter-model
        path: mannequin-segmenter/artifacts/20250703_190222/checkpoint.pt
        retention-days: 7 